config:
    send_anonymous_usage_stats: False
    use_colors: True
    partial_parse: True

mybi_dbt_ramm:
  target: prod
  outputs:
    prod:
      type: clickhouse
      schema: dbt
      host: "{{ env_var('DBT_HOST') }}"
      port: 8443
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      secure: True
      verify: False
      threads: 1
    dev:
      type: clickhouse
      schema: dev
      host: "{{ env_var('DBT_HOST') }}"
      port: 8443
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      secure: True
      threads: 1
    # ci:
    #   type: clickhouse
    #   schema: "{{ env_var('DBT_SCHEMA') }}"
    #   host: "{{ env_var('DBT_HOST') }}"
    #   port: "{{ env_var('DBT_PORT') | int }}"
    #   user: "{{ env_var('DBT_USER') }}"
    #   password: "{{ env_var('DBT_PASSWORD') }}"
    #   threads: 3  
